<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>OnEkYeniYili</name>
   <tag></tag>
   <elementGuidId>15a1100e-8dd6-47fe-84bf-71bdd3b6686f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[2]/div/form/div/div[1]/div/div/table/tbody/tr[2]/td/div/table/tbody/tr/td/div/div/div/div/div[1]/div/table/tbody/tr/td/div[2]/table/tbody/tr[2]/td[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[2]/div/form/div/div[1]/div/div/table/tbody/tr[2]/td/div/table/tbody/tr/td/div/div/div/div/div[1]/div/table/tbody/tr/td/div[2]/table/tbody/tr[2]/td[3]</value>
   </webElementProperties>
</WebElementEntity>
